moneyTransactionService:
#  repositoryImplementation: IN_MEMORY
#  repositoryImplementation: JOOQ
  repositoryImplementation: VERTX_PG
#  restImplementation: SPARK
  restImplementation: VERTX
  database:
    url: jdbc:postgresql://localhost:5435/money-transactions
    user: postgres
    password: postgres